name: Generate Person Data

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"  # Use the desired Python version

      - name: Install dependencies
        run: pip install csv
        run: pip install random # Add any necessary dependencies

      - name: Run person.py
        run: python person.py

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add person.csv
          git commit -m "Generate person.csv"
          git push
          
