name: Generate Person CSV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x


    - name: Run person.py
      run: python person.py

    - name: Move person.csv to code tab
      run: mv person.csv $GITHUB_WORKSPACE

    - name: Commit and push changes
      run: |
        git config --global user.name 'imxasik'
        git config --global user.email 'imxasik@gmail.com'
        git add .
        git commit -m "Update person.csv"
        git push
        
