name: Generate Person Data

on:
  push:
    paths:
      - 'person.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Use the desired Python version

    - name: Run Python Script
      run: python person.py

    - name: Upload CSV
      uses: actions/upload-artifact@v2
      with:
        name: person-data
        path: person.csv
      
