name: Generate CSV

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  generate-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Change this to your desired Python version

      - name: Install dependencies
      

      - name: Generate CSV
        run: python person.py

      - name: Commit and push CSV file
        run: |
          git config --global user.email "imxasik@gmail.com"
          git config --global user.name "imxasik"
          git add data/person.csv
          git commit -m "Add generated CSV file"
          git push
          
